set -e
true
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-hammer /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/corrected/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/corrected/corrected.yaml --ext_python_modules_home /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades --max_threads 8 --output_dir /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/corrected --gzip_output
true
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K21/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K33/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K55/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/copy_files.py /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/before_rr.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/before_rr.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/final_contigs.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/contigs.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/first_pe_contigs.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/first_pe_contigs.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/strain_graph.gfa /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/strain_graph.gfa /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/scaffolds.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/scaffolds.fasta /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/scaffolds.paths /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/scaffolds.paths /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/assembly_graph.fastg /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/assembly_graph.fastg /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/K77/final_contigs.paths /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/contigs.paths
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/scaffolds.fasta --misc_dir /Users/weeblesthe2nd/mtb_argentina_mdr/spadesout_trimmed_strict/misc --threshold_for_breaking_scaffolds 3
true
